name: Build Jar and Upload to Google Drive

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8' # Corrected to match JDK setup
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file 'demo/pom.xml'
    
    - name: list dir
      run: ls -al demo/target
      
    - name: Upload to Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: demo/target/demo-1.0-SNAPSHOT.jar

  
  upload-gdrive:
    runs-on: ubuntu-latest
    steps:
      - name: Donwload Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
      
      - name: Display structure of downloaded files
        run: ls -R
        
      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_API_KEY1 }}
          filename: "demo-1.0-SNAPSHOT.jar"
          folderId: ${{ secrets.GOOGLE_FOLDER }}
          overwrite: "true"
