name: Build Jar and Upload to Google Drive

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8' # Corrected to match JDK setup
        distribution: 'temurin'
        cache: maven
    - name: list dir
      run: ls -al
    - name: Build with Maven
      run: mvn -B package --file 'demo/pom.xml'

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  # upload_to_gdrive:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Archive files
  #     run: |
  #       sudo apt-get update
  #       sudo apt-get install zip
  #       zip -r archive.zip *

  #   - name: Upload to Google Drive
  #     uses: adityak74/google-drive-upload-git-action@main
  #     with:
  #       credentials: ${{ secrets.credentials }}
  #       filename: "archive.zip"
  #       folderId: ${{ secrets.folderId }}
  #       overwrite: "true"

  #   - name: Make Directory Structure
  #     run: |
  #       mkdir -p w/x/y
  #       date +%s > w/x/y/z

  #   - name: Mirror Directory Structure
  #     uses: adityak74/google-drive-upload-git-action@main
  #     with:
  #       credentials: ${{ secrets.DRIVE_CREDENTIALS }}
  #       filename: w/x/y/z
  #       folderId: ${{ secrets.folderId }}
  #       overwrite: "true"
  #       mirrorDirectoryStructure: "true"
